name: Integration tests!

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare SQL image
      working-directory: PrepareForWindows
      run: |
        .\build_mssql-server-windows.ps1

    - name: Test Docker on Windows
      if: startsWith(runner.os, 'Windows')
      working-directory: PrepareForWindows
      run: |
        docker run --name sql-container -d -p 1433:1433 -v C:/temp/:C:/temp/ -e sa_password=SQLServer2017 -e ACCEPT_EULA=Y -e attach_dbs="[]" -it mssql-server-windows

    - name: Test Docker on Windows2
      if: startsWith(runner.os, 'Windows')
      working-directory: PrepareForWindows
      run: |
        docker container logs mssql-server-windows

    - name: Test Docker on Windows3
      if: startsWith(runner.os, 'Windows')
      working-directory: PrepareForWindows
      run: |
        docker container logs sql-container
