name: Integration tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Containerized_integration_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Install Latest Docker
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
        sudo apt-get update
        sudo apt-get install docker-ce
        sudo apt-get install docker-compose-plugin
        sudo apt-get update
        sudo docker compose version

    - name: Build the SQL image
      working-directory: Prepare
      run: docker build -t sql-server:2017 . 

    - name: Build the Integration Tests image
      working-directory: DbIntegrationTestsDemo
      run: docker build -t integration-tests .

    - name: Containerized tests
      run: docker compose -f docker-compose.yml  up --exit-code-from integration-tests

    - name: Tear down services
      if: always()  # ensures this runs even if previous steps fail
      run: docker compose down