name: Integration tests!

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare SQL image
      working-directory: PrepareForWindows
      run: |
        .\build_mssql-server-windows.ps1

    - name: Prepare WebAppLegacy image
      working-directory: .
      run: |
        ls
        docker build -t webapp-legacy -f WebAppLegacyShowcase/Dockerfile . 

    - name: Containerized tests
      run: docker compose -f docker-compose.yml  up 

    - name: Tear down services
      if: always()  # ensures this runs even if previous steps fail
      run: docker compose down
