name: Integration tests!

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Test Docker on Windows
      if: startsWith(runner.os, 'Windows')
      working-directory: mssql-server-windows
      run: |
        docker pull mcr.microsoft.com/mssql/server:2019-latest
        #docker run -d -p 1433:1433 -v C:/temp/:C:/temp/ -e sa_password=SQLServer2017 -e ACCEPT_EULA=Y -e attach_dbs="[]" microsoft/mssql-server-windows