name: Integration tests!

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Test Docker on Windows
      if: startsWith(runner.os, 'Windows')
      run: |
        docker pull hello-world
        docker --version
        docker compose --version